name: Deploy and Update Codes

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 15,17,21 * * *'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Шаг 1: Клонирование репозитория
      - name: Checkout repository
        uses: actions/checkout@v3

      # Шаг 2: Настройка Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      # Шаг 3: Установка зависимостей
      - name: Install dependencies
        run: npm install

      # Шаг 4: Запуск скрипта для обновления names.json
      - name: Run fetchCodes script
        run: node scripts/fetchCodes.js

      # Шаг 5: Деплой на GitHub Pages
      - name: Build and deploy
        run: |
          npm run build
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Action"
          git checkout --orphan gh-pages
          git --work-tree build add --all
          git --work-tree build commit -m "GitHub Pages deployment"
          git push origin HEAD:gh-pages --force
